In [1]:
import pickle
import pandas as pd

ratings = pickle.load( open( "save.p", "rb" ) )

In [2]:
ratingsPD = pd.DataFrame(ratings, columns=['user', 'item', 'rating'] )
ratingsPD.head()

   user  item  rating
0     0     2    29.0
1     0     9     6.0
2     0    15   100.0
3     0    17     4.0
4     0    24     4.0

In [3]:
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler([1,5])
def fx(x):
    data = preprocessing.scale(x['rating'].to_numpy().reshape(-1, 1))
    scaler.fit(data)
    data=scaler.transform(data)
    x['rating']=data
    return x
ratingsPD = ratingsPD.groupby('user').apply(fx)

In [4]:
ratingsPD1= ratingsPD.groupby('user').filter(lambda x : len(x)>24)

In [5]:
ratingsPD2 = ratingsPD1.groupby('item').filter(lambda x : len(x)>3)

In [6]:
ratings =ratingsPD2

In [7]:
len(ratings)

2160797

In [10]:
ratings.groupby('user').count()

      item  rating
user
0     3340    3340
1      562     562
2     6717    6717
3     1339    1339
4     1088    1088
5     1031    1031
6       81      81
7      395     395
8      322     322
9      646     646
10     495     495
11     336     336
12    1597    1597
13    1549    1549
14     329     329
15     409     409
16    1089    1089
17     411     411
18     133     133
19    1133    1133
20     740     740
21     353     353
22     417     417
23    1027    1027
24     168     168
25     124     124
26     751     751
27    1066    1066
28    1177    1177
29     435     435
...    ...     ...
5423    47      47
5424    48      48
5425   320     320
5427   105     105
5428    36      36
5429   447     447
5430   136     136
5431    31      31
5432    26      26
5433    92      92
5434    36      36
5435    71      71
5436   492     492
5437   399     399
5438   121     121
5440    48      48
5441   148     148
5442    89      89
5443    30      30
5444    21      21
5445    54      54
5446   169     169
5447    93      93
5448    17      17
5449    86      86
5450   515     515
5451   109     109
5452    61      61
5453    57      57
5455    23      23

[5345 rows x 2 columns]

In [11]:
ratings['item'].nunique()

77448

In [8]:
import lenskit
from lenskit.algorithms.basic import Bias
from lenskit.metrics.predict import rmse

from lenskit import batch, topn, util
from lenskit import crossfold as xf
from lenskit.algorithms import Recommender, als, item_knn as knn, user_knn as uknn, funksvd
from lenskit.algorithms.basic import Fallback
from lenskit import topn
from lenskit.algorithms.basic import Bias
rm = 0
for train, test in xf.partition_users(ratings[['user', 'item', 'rating']], 5,xf.SampleFrac(0.3)):
    pred = als.BiasedMF(45)
    #rec = Recommender.adapt(pred)
    pred.fit(train)
    preds = batch.predict(pred, test)
    #print(preds['prediction'].isna().sum())
    print((rmse(preds['prediction'], preds['rating'],missing ='ignore')))
    rm+= (rmse(preds['prediction'], preds['rating'],missing ='ignore'))
print("Average RMSE: " + str(rm/5))

0.3871935452417445
0.39152330248956596
0.4057833582662802
0.3989173256907077
0.39571182090095136
Average RMSE: 0.39582587051784995

In [ ]:
import lenskit
from lenskit.algorithms.basic import Bias
from lenskit.metrics.predict import rmse

from lenskit import batch, topn, util
from lenskit import crossfold as xf
from lenskit.algorithms import Recommender, als, item_knn as knn, user_knn as uknn, funksvd
from lenskit.algorithms.basic import Fallback
from lenskit import topn
from lenskit.algorithms.basic import Bias
rm = 0
for train, test in xf.partition_users(ratings[['user', 'item', 'rating']], 5,xf.SampleFrac(0.3)):
    pred = als.ImplicitMF(45)
    #rec = Recommender.adapt(pred)
    pred.fit(train)
    preds = batch.predict(pred, test)
    #print(preds['prediction'].isna().sum())
    print((rmse(preds['prediction'], preds['rating'],missing ='ignore')))
    rm+= (rmse(preds['prediction'], preds['rating'],missing ='ignore'))
print("Average RMSE: " + str(rm/5))