In [45]:
import pickle
import pandas as pd

ratings = pickle.load( open( "saveAll.p", "rb" ) )

In [46]:
ratingsPD = pd.DataFrame(ratings, columns=['user', 'item', 'rating'] )
ratingsPD.head()

   user  item  rating
0     0    17     3.0
1     0    29   153.0
2     0    42     7.0
3     0    46   518.0
4     0    47     5.0

In [47]:
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
scaler = preprocessing.MinMaxScaler([1,5])
def fx(x):
    data = preprocessing.scale(x['rating'].to_numpy().reshape(-1, 1))
    scaler.fit(data)
    data=scaler.transform(data)
    x['rating']=data
    return x
ratingsPD = ratingsPD.groupby('user').apply(fx)

In [48]:
ratingsPD1= ratingsPD.groupby('user').filter(lambda x : len(x)>25)
ratingsPD2 = ratingsPD1.groupby('item').filter(lambda x : len(x)>3)
ratings = ratingsPD2

In [49]:
len(ratings)

27265784

In [50]:
ratings['item'].nunique()

428623

In [51]:
ratings['user'].nunique()

42345

In [52]:
ratingsPD.groupby('item').count().sort_values(by=['user'], ascending=False).head(50)

       user  rating
item
1465  19022   19022
45    18769   18769
313   18439   18439
132   17488   17488
26    16789   16789
150   16643   16643
137   16536   16536
234   16110   16110
15    16071   16071
354   15326   15326
53    14890   14890
1535  14573   14573
861   14558   14558
2     14532   14532
483   14367   14367
283   14364   14364
288   14278   14278
342   14021   14021
365   14018   14018
259   13856   13856
1511  13568   13568
54    13561   13561
1641  13557   13557
294   13391   13391
136   13321   13321
3849  13305   13305
1529  13301   13301
1508  13267   13267
407   13245   13245
652   12988   12988
182   12924   12924
241   12863   12863
134   12852   12852
450   12669   12669
142   12539   12539
160   12512   12512
2361  12441   12441
98    12406   12406
321   12400   12400
129   12397   12397
78    12385   12385
1562  12371   12371
3479  12327   12327
253   12221   12221
2367  12138   12138
31    12137   12137
337   11921   11921
1255  11877   11877
386   11845   11845
84    11834   11834

In [53]:
indexNames = ratingsPD.groupby('item').count().sort_values(by=['user'], ascending=False)[ ratingsPD.groupby('item').count().sort_values(by=['user'], ascending=False)['user'] > 11834 ].index

In [54]:
list(indexNames)

[1465,
 45,
 313,
 132,
 26,
 150,
 137,
 234,
 15,
 354,
 53,
 1535,
 861,
 2,
 483,
 283,
 288,
 342,
 365,
 259,
 1511,
 54,
 1641,
 294,
 136,
 3849,
 1529,
 1508,
 407,
 652,
 182,
 241,
 134,
 450,
 142,
 160,
 2361,
 98,
 321,
 129,
 78,
 1562,
 3479,
 253,
 2367,
 31,
 337,
 1255,
 386]

In [55]:

ratingsPD = ratingsPD[ratingsPD['item'].isin(indexNames)]

In [56]:
ratingsPD.groupby('user').head()

           user  item    rating
5             0    53  1.194107
6             0    54  1.031196
15            0   241  1.017331
26            0  1255  1.010399
29            0  1465  1.024263
324           1    15  1.311864
326           1    31  1.027119
328           1    53  1.000000
331           1    98  1.040678
336           1   129  1.366102
2281          2     2  1.296296
2282          2    15  3.222222
2283          2    31  1.000000
2284          2    98  1.000000
2285          2   134  1.000000
2530          3     2  1.037915
2531          3    15  1.066351
2533          3    26  1.000000
2535          3    31  1.938389
2537          3    45  1.104265
4802          5     2  1.286853
4806          5    15  1.143426
4807          5    26  1.095618
4808          5    31  1.478088
4810          5    45  1.828685
6904          6     2  1.120200
6906          6    15  1.006678
6908          6    26  1.020033
6909          6    31  1.000000
6911          6    45  1.000000
...         ...   ...       ...
27616324  42884   259  1.148148
27616330  42884  1641  1.296296
27616359  42885    45  1.000000
27616362  42885   132  5.000000
27616367  42885   259  1.000000
27616370  42885  1255  1.000000
27616451  42886     2  1.296296
27616453  42886    31  1.207407
27616455  42886    45  1.074074
27616458  42886   132  1.000000
27616459  42886   134  1.014815
27616979  42887   259  1.000000
27616989  42888   321  3.666667
27617263  42892   134  3.000000
27617264  42892   337  1.000000
27617265  42892   342  1.000000
27617329  42893    45  1.000000
27617332  42893   142  1.013267
27617339  42893   283  1.000000
27617340  42893   294  1.000000
27617342  42893   313  1.630182
27619734  42894   313  1.000000
27619833  42896   234  1.285714
27619850  42897   354  5.000000
27619917  42899   321  3.666667
27619943  42900    45  1.493739
27619946  42900   137  1.486583
27619947  42900   150  1.000000
27619951  42900   234  2.223614
27619952  42900   259  1.257603

[186593 rows x 3 columns]

In [61]:
list(ratingsPD.item.unique())

[53,
 54,
 241,
 1255,
 1465,
 1511,
 15,
 31,
 98,
 129,
 132,
 137,
 288,
 313,
 321,
 337,
 342,
 354,
 365,
 1535,
 1562,
 2361,
 2367,
 3849,
 2,
 134,
 182,
 234,
 407,
 26,
 45,
 78,
 142,
 150,
 253,
 259,
 294,
 483,
 861,
 1508,
 1529,
 1641,
 283,
 450,
 652,
 386,
 3479,
 136,
 160]

In [67]:
scaler = preprocessing.MinMaxScaler([1,50])
scaler.fit(list(ratingsPD.item.unique().reshape(-1, 1)))
ratingsPD['newItem'] = scaler.transform(ratingsPD['item'].to_numpy().reshape(-1, 1))

In [68]:
ratingsPD

           user  item    rating    newItem
5             0    53  1.194107   1.649597
6             0    54  1.031196   1.662334
15            0   241  1.017331   4.044190
26            0  1255  1.010399  16.959709
29            0  1465  1.024263  19.634520
31            0  1511  1.055459  20.220432
324           1    15  1.311864   1.165584
326           1    31  1.027119   1.369379
328           1    53  1.000000   1.649597
331           1    98  1.040678   2.222771
336           1   129  1.366102   2.617624
337           1   132  1.596610   2.655836
338           1   137  1.013559   2.719522
350           1   288  1.311864   4.642839
353           1   313  1.081356   4.961269
354           1   321  2.179661   5.063166
356           1   337  1.230508   5.266961
358           1   342  1.000000   5.330647
359           1   354  1.040678   5.483494
360           1   365  1.000000   5.623603
394           1  1255  1.027119  16.959709
402           1  1465  1.135593  19.634520
404           1  1511  1.013559  20.220432
407           1  1535  1.122034  20.526124
410           1  1562  1.013559  20.870029
465           1  2361  1.149153  31.047050
467           1  2367  1.108475  31.123473
576           1  3849  1.013559  50.000000
2281          2     2  1.296296   1.000000
2282          2    15  3.222222   1.165584
...         ...   ...       ...        ...
27616979  42887   259  1.000000   4.273460
27616989  42888   321  3.666667   5.063166
27617263  42892   134  3.000000   2.681310
27617264  42892   337  1.000000   5.266961
27617265  42892   342  1.000000   5.330647
27617329  42893    45  1.000000   1.547700
27617332  42893   142  1.013267   2.783208
27617339  42893   283  1.000000   4.579153
27617340  42893   294  1.000000   4.719262
27617342  42893   313  1.630182   4.961269
27617343  42893   321  5.000000   5.063166
27617347  42893   483  1.000000   7.126592
27617416  42893  2361  1.000000  31.047050
27619734  42894   313  1.000000   4.961269
27619833  42896   234  1.285714   3.955030
27619850  42897   354  5.000000   5.483494
27619917  42899   321  3.666667   5.063166
27619943  42900    45  1.493739   1.547700
27619946  42900   137  1.486583   2.719522
27619947  42900   150  1.000000   2.885105
27619951  42900   234  2.223614   3.955030
27619952  42900   259  1.257603   4.273460
27619954  42900   288  1.000000   4.642839
27619957  42900   354  1.379249   5.483494
27619958  42900   365  1.021467   5.623603
27619962  42900   407  1.000000   6.158565
27619974  42900   861  1.100179  11.941253
27619975  42900  1465  1.028623  19.634520
27619976  42900  1508  1.271914  20.182220
27619978  42900  1529  1.336315  20.449701

[683379 rows x 4 columns]

In [10]:
import lenskit
from lenskit.algorithms.basic import Bias
from lenskit.metrics.predict import rmse

from lenskit import batch, topn, util
from lenskit import crossfold as xf
from lenskit.algorithms import Recommender, als, item_knn as knn, user_knn as uknn, funksvd
from lenskit.algorithms.basic import Fallback
from lenskit import topn
from lenskit.algorithms.basic import Bias

rm = 0

for train, test in xf.partition_users(ratings[['user', 'item', 'rating']], 5, xf.SampleFrac(0.2)):
    pred = als.BiasedMF(45)
    rec = Recommender.adapt(pred)
    pred.fit(train)
    preds = batch.predict(pred, test)
    print(preds['prediction'].isna().sum())
    print((rmse(preds['prediction'], preds['rating'],missing ='ignore')))
    rm+= (rmse(preds['prediction'], preds['rating'],missing ='ignore'))
print("Average RMSE: " + str(rm/5))

0
0.33308603563796746
0
0.33090071233699403
0
0.33492574233861877
4
0.3345198537603395
0
0.3319590372805881
Average RMSE: 0.3330782762709016

In [ ]:
import lenskit
from lenskit.algorithms.basic import Bias
from lenskit.metrics.predict import rmse

from lenskit import batch, topn, util
from lenskit import crossfold as xf
from lenskit.algorithms import Recommender, als, item_knn as knn, user_knn as uknn, funksvd
from lenskit.algorithms.basic import Fallback
from lenskit import topn
from lenskit.algorithms.basic import Bias

for train, test in xf.partition_users(ratings[['user', 'item', 'rating']], 5, xf.SampleFrac(0.2)):
    pred = als.BiasedMF(20)
    base = Bias(damping=5)
    #rec = Recommender.adapt(pred)
    fall = Fallback(pred,base)
    fall.fit(train)
    preds = batch.predict(fall, test)
    print(preds.head())
    print((rmse(preds['prediction'], preds['rating'],missing ='ignore')))